name: business_invoice_generator_app
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  cloud_firestore: ^5.6.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mailto: ^2.0.0
  path: ^1.8.3
  path_provider: ^2.1.5
  pdf: ^3.11.1
  pdfx: ^2.8.0
  printing: ^5.13.4
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  share_plus: ^7.2.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.0
  riverpod_generator: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  # assets:
    # Add assets from the images directory to the application.
    # - assets/images/
